# Data Curation Standards

The goal of the Data Team when archiving, sharing, and preserving data products (datasets and derived data products) is to reduce data uncertainty and serve specific designated communities including the source community. Datasets and derived data products are archived according to the Open Archival Information System (OAIS) and the FAIR standards of scientific data management. They are shared in a way that protects and respects TIES survey respondents. 

|   | Raw Datasets | Internal Datasets| Replication/Verification Datasets | Reuse datasets |
|---|---|---|---|---| 
|**Designated Communities** | TIES Data Team| TIES Staff | Academic and scholarly users | Academic and scholarly users, host country (government) users, NGO users|
|**Metadata Requirements** | None | limited | targeted towards academic use including academic schemas | complete DDI codebook |
|**Language / Internationalization standards**| None | English and language of host country | English and language of article | English and language of host country |
|**Derived data products**| Internal datasets | Internal reports, policy briefs, presentations | academic articles | policy briefs, presentations |
|**Repository / Storage solution**| according to DUA/DMP | according to DUA/DMP | journal approved or sponsored repository | Harvard Dataverse |
|**Deidentification/Anonymization level** | None | Deidentified | Anonymized | Anonymized |
|**Quality Assurance Level** | Low | Medium | High | High |

---

Below are a list of general concepts followed by various standards for different kinds of datasets. The appendix has background material/definitions for common curation practices.

**Data Uncertainty**: This is the degree to which data is inaccurate, imprecise, untrusted, or unknown. All complex systems have a degree of uncertainty inherent within them. Practically this means that when designing data products, efforts should be made to reduce or remove missingness and ensure that data products are properly described with metadata/documentation where applicable.

**Desginated Community**: This is the audience for a data product and can be an imagined group or persona. The term is borrowed from the Open Archival Information System (OAIS) Reference Model and defined as “an identified group of potential Consumers who should be able to understand a particular set of information.” Each designated community has its own Knowledge Base. The Knowledge Base of a DC can change over time to the point where the archive would need to update and enhance preserved information to make it understandable again for the DC.

**Conceptual Structure**: The conceptual structure of a dataset exists in the metadata and consists of controlled vocabularies that exist as permanent URLs. It defines the concepts that underlies the elements and variables and increases interoperability.

---

## Raw Dataset Standards


Datasets of raw data from the data collector. Has identifiable information and can be multiple files. 

Basic study level metadata is collected or collated from preregistrations and pre-analysis plans. Variable level metadata is limited to variable names and labels. At this stage there is no conceptual structure.

Due to the sensitive nature of these data, Data use agreements and data management plans disallow the sharing of these datasets. The only derived product from raw data are in process deidentified datasets designated for internal use.

---

## Internal Datasets Standards

Data that is being processed by the Data Team but available to other Global TIES staffmembers. This data is in the process of being cleaned and deidentified. 

At this point study and variable level metadata has been moved into a YAML file and follows the DDI-Codebook (2.5) schema. The metadata is focused on the needs of TIES staff and partners, therefore it does not yet include a conceptual structure for interoperability. 

Terms of use are still determined by the data use agreement and data management plan. Typically, this data is not shared outside of partners or through an application procedure. The data is also held according to the DUA and DMP, usually in an NYU storage solution (Box) or in private repositories.

As the data is prepared, deidentified, and getting close to finalized, derived data products may be created from it, namely data dictionaries, policy briefs, presentations, and funder reports. Metadata shared with funder reports may be multilingual in the language of the funder or partner. 

---

## Replication/Verification Datasets Standards

These datasets are generated in support of an academic derived data product (article, presentation, poster). Data is limited to the variables and measures used in the academic work and is produced in a single csv file. These datasets may include code used to generate the derived data product.

Metadata is generated in a DDI-Codebook and as documentation in a pdf. Study level metadata is focused on discovery and linked to the published article. Variable level metadata have labels and categories. A conceptual structure constructed from academic controlled vocabularies is used.

Data is licensed using a standard or custom license depending on the sensitivity of the data.

---

## Datasets for Reuse Standards

These datasets are designed for reuse on a wider scale than a replication/verification dataset. Here, all variables in a study are included, as long as there's no potential harm to the data subject. In cases where the inclusion of a variable may lead to the risk of identification, it may be embargoed or recoded to limit risk. 

The metadata is generated in a DDI-Codebook and as documentation in a pdf. Study level metadata is complete, with conceptual structures to address a larger designated community than other datasets. Variable level metadata includes a data dictionary, variable grouping, conceptual structures, and summary statistics, including visualizations where appropriate. 

Datasets are deposited in FAIR repositories that provide the most discoverability. Currently, we deposit reuse datasets in Harvard Dataverse because it is indexed in Google Dataset Search. The data is licensed under a custom license to increase protection of our data subjects. 

---

## Protecting data subjects: Curation tactices 

---

## Appendix

### Citation formats

#### Data Citation

We use the DataCite format to cite datasets (https://datacite.org/cite-your-data.html). The basic citation format is as follows:

- Creator (PublicationYear). Title. Publisher. Identifier

There are also two optional properties. If used the citation format is:

- Creator (PublicationYear). Title. Version. Publisher. ResourceType. Identifier.

The APA style guide also has a dataset citation format:

- Author or Rightsholder, A. A. (Year). Title (Version Number) [Description of Form]. Publisher. Identifier or URL.

The Datacite format is preferable because it’s an open format and the DOI registration agency for datasets. There’s no differentiation between Publisher and Distributor in the citations. My preference is to include both in order to recognize the publishers (like Global TIES & IRC) and distributor (repository).

- Creators (Publication Year). Title. Publisher [Publisher]. Distributor [distributor]. Identifier.

#### Academic works citation

We use APA citation style to cite articles, books, and preprints. The below cases are 6th edition. 

**Articles**

- Last Name, First Initial. Second Initial. (Year). Title. Journal, Volume(Issue), pages. DOI link.

**Book**

- Author last name, First Initial. Second Initial. (Year). Book title: Subtitle. Publisher. URL
- Author last name, First Initial. Second Initial. (Ed.). (Year). Book title: Subtitle. Publisher. URL link

**Book chapter**

- Chapter Author’s Last Name, First Initial. Second Initial. (Year). Chapter title. In Editor First initial. Second  Initial. Editor Last Name (Ed.). Book title: Subtitle (edition, Volume, pages). Publisher Name. identifier or url link.

**Conference sessions, poster abstracts and poster presentations**

- Presenter last name, First initial. Second initial (date of conference). Title of presentation or poster [type of work]. Conference title. Conference location. URL or identifier link.

**Preprint**

- Last Name, First Initial. Second Initial. (Year). Title. Preprint repository. URL or DOI link.

#### Research instrument citation

We use APA citation style to cite research instrumentation (surveys, items, etc).

- Author last name, First initial., Second initial. (Year). Title [format of work]. URL or doi link.

#### Derived data product citation

We use APA citation style to cite derived data products, preferably hosted on figshare. 

**Visual (video or photograph) or audio work**

- Creator last name, First initial. Second Initial. (Year, Month Day). Title of work [Description of media, graph or table]. Source. URL or DOI link.

**Policy Brief or report**

- Organization (Year, Month Day). Title of work [Policy brief or report]. Source. URL or DOI link.

---

### Data Management Plans

Data Management Plans (DMP) are living documents that outline how data will be managed, secured, shared, archived, and destroyed (if necessary). They are based on organizational policies and capabilities as well as the Data Use Agreement with the funder(s) and IRB proposals and approvals. Below are three sample DMPs.

#### TIES owns raw and processed data

**Data Management Plan**

*Research Products*

This data management plan outlines the expectations of data storing, sharing, dissemination, and archiving for any project that may use funds from this <insert name> proposal. Any project using funds from this proposal planning to collect data on human subjects must have IRB approval.

*Internal Data Sharing*

All data will be retained for a period of no less than three years per NYU's Data Retention and Access Policy. Copies of all data will be kept on NYU Box, which performs regular backups. To facilitate streamlined data pipelines, data may also be stored on a NYU Global TIES for Children (NYU-TIES) instance of the Open Science Framework (OSF), Github, or another version control capable  repository host<insert options>. Any raw, identifiable data collected through a variety of methods (e.g., surveys, interview protocols, structured observations, administrative data, implementation data) will only be available to the research and data teams for quality assurance, processing, preliminary analysis, and anonymization.. Only anonymized data will be used for published or publicly presented analysis. Identifiable data used during the cleaning process will be encrypted in transit and at rest.

*Collaboration with Partners or Subcontractors*

Should data collection be handled by a partner organization, the partner and/or subcontractor must have their own IRB and a DMP approved by NYU-TIES that governs data collection and management. NYU-TIES will also submit its own IRB proposal adhering to the guidelines outlined herein for the receipt of any identifiable data. The partner must ensure that the data is encrypted at rest and in transit. The partner and NYU-TIES shall hold joint ownership of the data. Ownership of and access to the derived data products shall be guided by the agreement between NYU-TIES and the partner and/or subcontractor.

*Dissemination, Access, and Sharing of Unpublished Data*

All shared data will be accompanied by data dictionaries, metadata that describe the content of the data. The data dictionaries will adhere to the Data Documentation Initiative (DDI) 2.5 or above standard to maximize long-term shareability. Deidentified data sharing prior to publication will be managed on a case-by-case basis, approved by the PI and Co-PI. Individuals wishing to acquire data in this manner must sign a data use agreement, authored by NYU-TIES, that includes a requirement to destroy copies of the data once the sharing agreement terminates. Raw, identifiable data will never be shared. Deidentified data will be published on our Dataverse instance on the Harvard Dataverse. The data may be subject to an embargo, allowed up to one year after the end of this proposal’s period end. Details about methodology will be hosted on the shareable data's respective Dataverse repository, as well as copies of all measures used. 

Code and supplemental artifacts that help generate the published data will be hosted on an Open Science Framework project. All published assets will be licensed with a Creative Commons Attribution Share-Alike license.

*Data Archiving and Publishing*

Any raw or potentially identifiable data will be preserved on NYU Box for a period of no less than three years. Code and supplemental artifacts that help generate the published data will be hosted on an Open Science Framework project. 

The Data Team within NYU-TIES will manage and curate any published project or replication data for publications by depositing itted to a FAIRthe Dataverse repository listed in re3data.org, the Registry of Research Data Repositories. Data may be subject to an embargo, allowed up to one year after the end of this proposal’s period end. Details about methodology will be hosted on the shareable data's respective repository in the metadata and documentation. 

Data will be published with a custom license that protects the identities and wellbeing of the subjects. In situations where an open data license is suitable, data will be published using an open data license, like  the Open Data Commons Attribution License. All concurrent metadata and documentation will be licensed with a Creative Commons Attribution or Attribution Share-Alike license. Destruction of the identifiable raw data will follow NYU's Data Retention and Access Policy and other relevant policies. 

#### TIES  shares ownership with data collector

**Data Management Plan**

*Research Products*

This data management plan outlines the expectations of data storing, sharing, dissemination, and archiving for any project that may use funds from this <insert name> proposal in coordination with <insert partner name>, the data collector. Any project using funds from this proposal planning to collect data on human subjects must have IRB approval.

*Internal Data Sharing*

All data will be retained for a period of no less than three years per NYU's Data Retention and Access Policy. Copies of all data will be kept on NYU Box, which performs regular backups. To facilitate streamlined data pipelines, data may also be stored on a NYU Global TIES for Children (NYU-TIES) instance of the Open Science Framework (OSF), Github, or another version control capable  repository host. NYU Box is password-protected and requires multiple levels of authentication. Any raw, identifiable data collected through a variety of methods (e.g., surveys, interview protocols, structured observations, administrative data, implementation data) will only be available to the research and data teams for quality assurance, processing, preliminary analysis, and anonymization.. Only anonymized data will be used for published or publicly presented analysis. Identifiable data used during the cleaning process will be encrypted in transit and at rest.

*Collaboration with Partners or Subcontractors*

Data collection is to be handled by <name of partner organization>. <Partner organization> has their own IRB and a DMP that governs data collection and management. NYU-TIES will also submit its own IRB proposal adhering to the guidelines outlined herein for the receipt of any identifiable data. The partner must ensure that the data is encrypted at rest and in transit. The partner and NYU-TIES shall hold joint ownership of the <processed/raw/all>) data and derived datasets(?). 

All subcontractors must have their own IRB and a DMP that governs data collection and management. NYU-TIES and <partner organization name> will maintain co-ownership over the data. At the end of the contract the subcontractor must agree to destroy the data in accordance to NYU-TIES and <partner organization> policies. Ownership of and access to the derived data products created by the subcontractor shall be guided by the agreement between NYU-TIES and the partner and/or subcontractor.

*Dissemination, Access, and Sharing of Unpublished Data* 

All shared data will be accompanied by data dictionaries, metadata that describe the content of the data. The data dictionaries will adhere to the Data Documentation Initiative (DDI) 2.5 or above standard to maximize long-term shareability. Deidentified data sharing prior to publication will be managed on a case-by-case basis, approved by the PI and Co-PI. Individuals wishing to acquire data in this manner must sign a data use agreement, authored by NYU-TIES, that includes a requirement to destroy copies of the data once the sharing agreement terminates. Raw, identifiable data will never be shared. 

*Data Archiving and Publishing*

Any raw or potentially identifiable data will be preserved on NYU Box for a period of no less than three years. Code and supplemental artifacts that help generate the published data will be hosted on an Open Science Framework project. 

The Data Team within NYU-TIES will manage and curate any published project or replication data for publications by depositing it to a FAIR listed in re3data.org, the Registry of Research Data Repositories. Data may be subject to an embargo, allowed up to one year after the end of this proposal’s period end. Details about methodology will be hosted on the shareable data's respective repository in the metadata and documentation. 

Data will be published with a custom license that protects the identities and wellbeing of the subjects. In situations where an open data license is suitable, data will be published using an open data license, like  the Open Data Commons Attribution License. All concurrent metadata and documentation will be licensed with a Creative Commons Attribution or Attribution Share-Alike license. Destruction of the identifiable raw data will follow NYU's Data Retention and Access Policy and other relevant policies. 

#### TIES  is a subcontractor without ownership

**Data Management Plan**

*Research Products*

This data management plan outlines the expectations of data storing, sharing, dissemination, and archiving for any project that may use funds from this <insert name> proposal in coordination with <insert partner name>, the data owner. Any project using funds from this proposal planning to collect data on human subjects must have IRB approval. NYU-TIES is not responsible for the data quality of the data provided by <insert partner name>.

*Internal Data Sharing*

All data will be retained for the duration of the relationship between NYU-TIES and <data owner> according to the terms of data use agreement. Copies of all data will be kept on NYU Box, which performs regular backups. To facilitate streamlined data pipelines, data may also be stored on a NYU Global TIES for Children (NYU-TIES) instance of the Open Science Framework (OSF), Github, or another version control capable  repository host. NYU Box is password-protected and requires multiple levels of authentication. If provided by the data owner, any raw, identifiable data collected through a variety of methods (e.g., surveys, interview protocols, structured observations, administrative data, implementation data) will only be available to the research and data teams for quality assurance, processing, and anonymization. Only anonymized data will be used for analytical uses according to the terms of the data use agreement with <insert partner name>. Identifiable data used during the cleaning process will be encrypted in transit and at rest. Identifiable data used during the cleaning process will be encrypted in transit and at rest.

*Collaboration with Partners or Subcontractors*

Data will be provided by <name of partner organization>. <Partner organization> has their own IRB and a DMP that governs data collection and management. NYU-TIES will also submit its own IRB proposal adhering to the guidelines outlined herein for the receipt of any identifiable data. The data owner must ensure that the data is encrypted at rest and in transit. NYU-TIES shall hold access rights to the data and derived datasets/data products in line with the agreement with <data owner>. 

*Data Archiving and Publishing*

At the end of the contract NYU-TIES agrees to destroy the provided data in accordance with NYU-TIES and <data owner> policies and data use agreement. 

The Data Team within NYU-TIES will manage and curate any derived data products by depositing it to a FAIR listed in re3data.org, the Registry of Research Data Repositories, and according to the agreement with <data owner>. A derived data product is a data product produced by manipulating the original dataset and may include new datasets, tables, graphics, analysis, and other products. These derived data products may be subject to an embargo, allowed up to one year after the end of this proposal’s period end. Details about methodology will be hosted on the repository in the metadata and documentation. 

Derived data products will be published according to the agreement with <data owner>. Open data will be published under the Open Data Commons Attribution License. All concurrent metadata and documentation will be licensed with a Creative Commons Attribution or Attribution Share-Alike license. 

---

### FAIR standards

These standards were published in 2016 by Mark Wilkinson in the journal Scientific Data (https://doi.org/10.1038/sdata.2016.18) and are considered the standard for scientific data assets and products. They can also be referred to as the FAIR Principles and are applied to data, metadata, and docuemntation.

FAIR stands for Findable, Accessible, Interoperable, and Reusable. These standards are intended for both humans and machines and apply to both human-readable and machine-readable files. 

**Findable** 

- (Meta)data are assigned globally unique and persistent identifiers
- Data are described with rich metadata
- Metadata clearly and explicitly include the identifier of the data they describe
- (Meta)data are registered or indexed in a searchable resource

**Accessible**

- (Meta)data are retrievable by their identifier using a standardized communication protocol
- The protocol is open, free and universally implementable
- The protocol allows for an authentication and authorisation where necessary
- Metadata should be accessible even when the data is no longer available

**Interoperable**

- (Meta)data use a  formal, accessible, shared, and broadly applicable language for knowledge representation
- (Meta)data use vocabularies that follow the FAIR principles
(Meta)data include qualified references to other (meta)data

**Reusable**

- (Meta)data are richly described with a plurality of accurate and relevant attributes
- (Meta)data are released with a clear and accessible data usage license
- (Meta)data are associated with detailed provenance
- (Meta)data meet domain-relevant community standards

List from https://www.go-fair.org/fair-principles/

---

### Terms

#### Badges to Acknowledge Open Practices (OSF)

#### Code

#### Copyleft

#### Controlled Vocabulary

#### Crossref

#### Crosswalk

#### Data Documentation Initiative (DDI)

#### Datacite

#### Dataset

The dataset is the data that is to be preserved and shared. Each dataset has a designated community that defines the linguistic and conceptual needs of the metadata and documentation. 

#### Derived Data Product

 A derived data product is the analysis or aggregation of the dataset for reports, visualizations, or further analysis.
 
#### DOI (Digital Object Identifier)

#### Embargo

#### Hierarchical data

#### Human Readable
 
#### Internationalization

According to the World Wide Web Consortium (W3C), internationalization is taking steps to develop content or applications in a way that will work for users from any culture, region, or language. Data Team standards state that we use internationalized and multilingual controlled vocabularies where and when feasible in our reuse datasets. 

#### JSON

#### LaTeX

#### Linked data

#### Machine Readable

#### markdown

#### Metadata

Metadata is the context, definitions, descriptions of the values in a dataset. This can include labels, study information, authorship, titles, funders, etc. 

#### Natural Language data

#### Open License

#### Open Science

TIES participates in open science where and when it doesn’t pose a risk to our sources. Open science is the movement to make scientific research (including publications, data, physical samples, and software) and its dissemination acceptable to the public with limited to no restrictions. 

The Data Team's contributions to data processing, including code and packages, are open source, available to the public through Github, and we work to publish them in a appropriate repositories. For R packages, the appropriate repository is CRAN (the Comprehensive R Archive Network).

We also follow FAIR principles, making certain that our datasets are accessible and our metadata is open. These datasets are anonymized/deidentified to protect the subjects. Where possible, we use multilingual information thesauri and controlled vocabularies to increase interoperability by the host countries of our studies. 

#### ORCID (Open Researcher and Contributor ID)

#### PID (Persistent Identifier)

#### Preservation file formats

#### Repositories

**Social Science Research Data Repositories**

- Dataverse
- Inter-uiversity Consortiium for POlitical and Social Research (ICPSR)
- Qualitative Data Repository (QDR)

**Research Lifecycle Repositories**

- Dryad
- Figshare
- Open Science Framework (OSF)
- Zenodo

**Code Repositories**

- Github
- Gitlab
- Bitbucket

**Domain Specific Repositories**

- Humanitarian Data eXchange

**Institutional Repositories**

- NYU Faculty Digital Archive

#### Schema

#### Tabular data

#### YAML

#### XML