---
title: Data Management Plans
author: Dan Woulfin
categories: [standards, curation, dmp]
---

<!--:dmp:standards:curation:irb:-->

Data Management Plans (DMPs) are living documents that outline how data will be managed, secured, shared, archived, and destroyed (if necessary). They are based on organizational policies and capabilities as well as the Data Use Agreement with the funder(s) and IRB proposals and approvals. Below are three sample DMPs.

## TIES owns raw and processed data

> **Data Management Plan**
> 
> *Research Products*
> 
> This data management plan outlines the expectations of data storing, sharing, dissemination, and archiving for any project that may use funds from this <insert name> proposal. Any project using funds from this proposal planning to collect data on human subjects must have IRB approval.
> 
> *Internal Data Sharing*
> 
> All data will be retained for a period of no less than three years per NYU's Data Retention and Access Policy. Copies of all data will be kept on NYU Box, which performs regular backups.
> To facilitate streamlined data pipelines, data may also be stored on a NYU Global TIES for Children (NYU-TIES) instance of the Open Science Framework (OSF), Github, or another version control capable  repository host<!-- TODO: insert options-->.
> Any raw, identifiable data collected through a variety of methods (e.g., surveys, interview protocols, structured observations, administrative data, implementation data) will only be available to the research and data teams for quality assurance, processing, preliminary analysis, and anonymization.
> Only anonymized data will be used for published or publicly presented analysis. Identifiable data used during the cleaning process will be encrypted in transit and at rest.
> 
> *Collaboration with Partners or Subcontractors*
> 
> Should data collection be handled by a partner organization, the partner and/or subcontractor must have their own IRB and a DMP approved by NYU-TIES that governs data collection and management. NYU-TIES will also submit its own IRB proposal adhering to the guidelines outlined herein for the receipt of any identifiable data. The partner must ensure that the data is encrypted at rest and in transit. The partner and NYU-TIES shall hold joint ownership of the data. Ownership of and access to the derived data products shall be guided by the agreement between NYU-TIES and the partner and/or subcontractor.
> 
> *Dissemination, Access, and Sharing of Unpublished Data*
> 
> All shared data will be accompanied by data dictionaries, metadata that describe the content of the data. The data dictionaries will adhere to the Data Documentation Initiative (DDI) 2.5 or above standard to maximize long-term shareability. Deidentified data sharing prior to publication will be managed on a case-by-case basis, approved by the PI and Co-PI. Individuals wishing to acquire data in this manner must sign a data use agreement, authored by NYU-TIES, that includes a requirement to destroy copies of the data once the sharing agreement terminates. Raw, identifiable data will never be shared. Deidentified data will be published on our Dataverse instance on the Harvard Dataverse. The data may be subject to an embargo, allowed up to one year after the end of this proposal’s period end. Details about methodology will be hosted on the shareable data's respective Dataverse repository, as well as copies of all measures used. 
> 
> Code and supplemental artifacts that help generate the published data will be hosted on an Open Science Framework project. All published assets will be licensed with a Creative Commons Attribution Share-Alike license.
> 
> *Data Archiving and Publishing*
> 
> Any raw or potentially identifiable data will be preserved on NYU Box for a period of no less than three years. Code and supplemental artifacts that help generate the published data will be hosted on an Open Science Framework project. 
> 
> The Data Team within NYU-TIES will manage and curate any published project or replication data for publications by depositing itted to a FAIRthe Dataverse repository listed in re3data.org, the Registry of Research Data Repositories. Data may be subject to an embargo, allowed up to one year after the end of this proposal’s period end. Details about methodology will be hosted on the shareable data's respective repository in the metadata and documentation. 
> 
> Data will be published with a custom license that protects the identities and wellbeing of the subjects. In situations where an open data license is suitable, data will be published using an open data license, like  the Open Data Commons Attribution License. All concurrent metadata and documentation will be licensed with a Creative Commons Attribution or Attribution Share-Alike license. Destruction of the identifiable raw data will follow NYU's Data Retention and Access Policy and other relevant policies. 

## TIES  shares ownership with data collector

> **Data Management Plan**
> 
> *Research Products*
> 
> This data management plan outlines the expectations of data storing, sharing, dissemination, and archiving for any project that may use funds from this <insert name> proposal in coordination with <insert partner name>, the data collector. Any project using funds from this proposal planning to collect data on human subjects must have IRB approval.
> 
> *Internal Data Sharing*
> 
> All data will be retained for a period of no less than three years per NYU's Data Retention and Access Policy. Copies of all data will be kept on NYU Box, which performs regular backups. To facilitate streamlined data pipelines, data may also be stored on a NYU Global TIES for Children (NYU-TIES) instance of the Open Science Framework (OSF), Github, or another version control capable  repository host. NYU Box is password-protected and requires multiple levels of authentication. Any raw, identifiable data collected through a variety of methods (e.g., surveys, interview protocols, structured observations, administrative data, implementation data) will only be available to the research and data teams for quality assurance, processing, preliminary analysis, and anonymization.. Only anonymized data will be used for published or publicly presented analysis. Identifiable data used during the cleaning process will be encrypted in transit and at rest.
> 
> *Collaboration with Partners or Subcontractors*
> 
> Data collection is to be handled by <name of partner organization>. <Partner organization> has their own IRB and a DMP that governs data collection and management. NYU-TIES will also submit its own IRB proposal adhering to the guidelines outlined herein for the receipt of any identifiable data. The partner must ensure that the data is encrypted at rest and in transit. The partner and NYU-TIES shall hold joint ownership of the <processed/raw/all>) data and derived datasets(?). 
> 
> All subcontractors must have their own IRB and a DMP that governs data collection and management. NYU-TIES and <partner organization name> will maintain co-ownership over the data. At the end of the contract the subcontractor must agree to destroy the data in accordance to NYU-TIES and <partner organization> policies. Ownership of and access to the derived data products created by the subcontractor shall be guided by the agreement between NYU-TIES and the partner and/or subcontractor.
> 
> *Dissemination, Access, and Sharing of Unpublished Data* 
> 
> All shared data will be accompanied by data dictionaries, metadata that describe the content of the data. The data dictionaries will adhere to the Data Documentation Initiative (DDI) 2.5 or above standard to maximize long-term shareability. Deidentified data sharing prior to publication will be managed on a case-by-case basis, approved by the PI and Co-PI. Individuals wishing to acquire data in this manner must sign a data use agreement, authored by NYU-TIES, that includes a requirement to destroy copies of the data once the sharing agreement terminates. Raw, identifiable data will never be shared. 
> 
> *Data Archiving and Publishing*
> 
> Any raw or potentially identifiable data will be preserved on NYU Box for a period of no less than three years. Code and supplemental artifacts that help generate the published data will be hosted on an Open Science Framework project. 
> 
> The Data Team within NYU-TIES will manage and curate any published project or replication data for publications by depositing it to a FAIR listed in re3data.org, the Registry of Research Data Repositories. Data may be subject to an embargo, allowed up to one year after the end of this proposal’s period end. Details about methodology will be hosted on the shareable data's respective repository in the metadata and documentation. 
> 
> Data will be published with a custom license that protects the identities and wellbeing of the subjects. In situations where an open data license is suitable, data will be published using an open data license, like  the Open Data Commons Attribution License. All concurrent metadata and documentation will be licensed with a Creative Commons Attribution or Attribution Share-Alike license. Destruction of the identifiable raw data will follow NYU's Data Retention and Access Policy and other relevant policies. 

## TIES  is a subcontractor without ownership

> **Data Management Plan**
> 
> *Research Products*
> 
> This data management plan outlines the expectations of data storing, sharing, dissemination, and archiving for any project that may use funds from this <insert name> proposal in coordination with <insert partner name>, the data owner. Any project using funds from this proposal planning to collect data on human subjects must have IRB approval. NYU-TIES is not responsible for the data quality of the data provided by <insert partner name>.
> 
> *Internal Data Sharing*
> 
> All data will be retained for the duration of the relationship between NYU-TIES and <data owner> according to the terms of data use agreement. Copies of all data will be kept on NYU Box, which performs regular backups. To facilitate streamlined data pipelines, data may also be stored on a NYU Global TIES for Children (NYU-TIES) instance of the Open Science Framework (OSF), Github, or another version control capable  repository host. NYU Box is password-protected and requires multiple levels of authentication. If provided by the data owner, any raw, identifiable data collected through a variety of methods (e.g., surveys, interview protocols, structured observations, administrative data, implementation data) will only be available to the research and data teams for quality assurance, processing, and anonymization. Only anonymized data will be used for analytical uses according to the terms of the data use agreement with <insert partner name>. Identifiable data used during the cleaning process will be encrypted in transit and at rest. Identifiable data used during the cleaning process will be encrypted in transit and at rest.
> 
> *Collaboration with Partners or Subcontractors*
> 
> Data will be provided by <name of partner organization>. <Partner organization> has their own IRB and a DMP that governs data collection and management. NYU-TIES will also submit its own IRB proposal adhering to the guidelines outlined herein for the receipt of any identifiable data. The data owner must ensure that the data is encrypted at rest and in transit. NYU-TIES shall hold access rights to the data and derived datasets/data products in line with the agreement with <data owner>. 
> 
> *Data Archiving and Publishing*
> 
> At the end of the contract NYU-TIES agrees to destroy the provided data in accordance with NYU-TIES and <data owner> policies and data use agreement. 
> 
> The Data Team within NYU-TIES will manage and curate any derived data products by depositing it to a FAIR listed in re3data.org, the Registry of Research Data Repositories, and according to the agreement with <data owner>. A derived data product is a data product produced by manipulating the original dataset and may include new datasets, tables, graphics, analysis, and other products. These derived data products may be subject to an embargo, allowed up to one year after the end of this proposal’s period end. Details about methodology will be hosted on the repository in the metadata and documentation. 
> 
> Derived data products will be published according to the agreement with <data owner>. Open data will be published under the Open Data Commons Attribution License. All concurrent metadata and documentation will be licensed with a Creative Commons Attribution or Attribution Share-Alike license. 

---

# See also

- [Curation](index.qmd)
