on:
  push:
    branches: [main]

name: quarto

jobs:
  quarto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install libcurl on Linux
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install needed R packages
        uses: r-lib/actions/setup-renv@v2

      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy to GitHub pages 🚀
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
